site_name: Dive into Keras Source Code
theme:
  favicon: img/favicon.png
  logo: img/logo.svg
  name: material

docs_dir: keras
repo_url: https://github.com/haifeng-jin/keras-source
site_url: https://haifeng-jin.github.io/keras-source
edit_uri: ""
site_description: "Dive into Keras Source Code"
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css

nav:
  - Introduction: index.md
  - 1. Modeling API overview: 01-modeling-api-overview.md
  - 2. The Layer class: 02-the-layer-class.md
  - 3. The Model class: 03-the-model-class.md
  - 4. The Functional class: 04-the-functional-class.md
  - 5. The Sequential class: 05-the-sequential-class.md
  - 6. Training API overview: 06-training-api-overview.md
  - 7. The compile function: 07-the-compile-function.md
  - 8. The fit function: 08-the-fit-function.md
  - 9. The predict function: 09-the-predict-function.md
  - 10. The evaluate function: 10-the-evaluate-function.md
  - 11. The losses: 11-the-losses.md
  - 12. The metrics: 12-the-metrics.md
